### ISSUE TITLE
Mismatch between paper and code in FocusNet++

### ISSUE THREAD

**Issue by pmgautam** [chaitanya-kaul/TheFocusNetSeries#1]
Hi authors,

I've been going through the FocusNet++ paper and code. I've found some differences between the paper and code. I've listed my findings below.
1. There's no SE block in code but is present in paper.
2. Paper mentions Groupwise convolutions but in code normal convolutions are used.
3. There is mismatch in filters used, filters in paper: (32, 64, 128, 192, 256), filters in code: (32, 48, 96, 156, 256, 512).
4. Residual block (code) contains conv -> BN -> LReLu which is not mentioned in code.

I wanted to know the reason for the differences and which one gives the best results.

Thanks in advance!

**Comment by chaitanya-kaul** [comment]
Hi,

Thanks for taking an interest in this code! To answer your questions, I'm assuming you're referring to focusnetpp.py here,

1. That is correct. Thanks for pointing this out! I seem to have uploaded one of the ablations here without the SE block. It can be added to the code in the following way -

from se import squeeze_excite_block

Then add this piece of code at line 195 in focusnetcpp.py

y = squeeze_excite_block(y)

That will do it!

2. Groupwise convolution is used in the code. This code is using an older version of keras when groupwise convolutions didn't exist as a simple function, and are hence coded from scratch here by dividing convolutions into groups, and then concatenating them.

3. Again, this is due to me trying different things with the code (because the convolutions have goups, they needed to be divided into multiples of those groups - eg. if you have 5 groups, filers should be in multiples of 5 and so on). The filters configuration used in the code here train slower but provide a slightly better performance (can get better SOTA with them), compared to the paper, which is slightly worse but quicker to train and have lot less FLOPS and parameters.

4. We had a more detailed 16 page paper on arxiv with all the information. The paper was finally published in ISBI 2021 which has a 4-5 page limit so we had to shorten the paper by cutting a lot out of it. Apologies if this ended up making it a bit more confusing!

Bottom line, if you add the SE block as in point 1 (or even if you run the code as is), you should notice a pretty high performance boost compared to the UNet and Attention UNet models. The FocusNet++ works really well even in this configuration and I'm sure you'll be surprised by how effective it can be compared to even today's medical image transformers on the same datasets.

I would also like to point out that the main idea of the paper wasn't SE block placements or simple layer engineering in terms of filters, but the fact that if you divide attention computation amongst filter groups, each unique group can learn an effective attention over individual parts of images well, that provides better performance compared to Attention UNet (which only attends encoder to decoder) and FocusNet and BCDUNet (which tend to be extremely bulky models). And this can be verified using the provided code!

**Comment by pmgautam** [comment]
Thank you for the information. This is really helpful.

**Comment by pmgautam** [comment]
Hello,

Can you please confirm the number of parameters? The model in this repo has around 7.7 M parameters which do not match with the number of parameters in the paper. Tables 2 and 3 in paper have 7.8 * 10 ** 8 and 1.84 * 10 ** 8 M parameters respectively. Both are higher than the one in the repo (table 2 has way too many parameters compared to the repo).
